const initDataJson = [
    {
        "groupTitle": "通用",
        "items": [
            { "type": "image_text", "name": "欧盟代表（名字、地址、邮箱）", "img": "https://recruit-student.51miniapps.com/tool/icon/221-ecrep.png", "content": "Name: \nAddress: \nEmail: " },
            { "type": "image_text", "name": "美国代表（名字、地址、邮箱）", "img": "https://recruit-student.51miniapps.com/tool/icon/us-rep.png", "content": "Name: \nAddress: \nEmail: " },
            { "type": "image_text", "name": "欧盟代表（名字、地址、邮箱）", "img": "https://recruit-student.51miniapps.com/tool/icon/eu-rep.png", "content": "Name: \nAddress: \nEmail: " },
            { "type": "image_text", "name": "土耳其代表（名字、地址、邮箱）", "img": "https://recruit-student.51miniapps.com/tool/icon/1/tur-rep.png", "content": "Ad: \nAdres: \nEmail: " },
            { "type": "image_text", "name": "英国代表（名字、地址、邮箱）", "img": "https://recruit-student.51miniapps.com/tool/icon/221-ukrep.png", "content": "Name: \nAddress: \nEmail: " },
            { "type": "image_text", "name": "土耳其代表（名字、地址、邮箱）", "img": "https://recruit-student.51miniapps.com/tool/icon/1/tr-rep.png", "content": "Ad: \nAdres: \nEmail: " },
            { "type": "text", "name": "CE类：欧盟进口商信息（包装）", "content": "For EU\nEU Importer Name: Whaleco Technology Limited\nEU Importer Address: First Floor, 25 St Stephens Green, Dublin 2, Ireland" },
            { "type": "text", "name": "英国进口商信息（包装）", "content": "For UK\nUK Importer Name: Whaleco UK Limited\nUK Importer Address: 5 Churchill Place, 10th Floor, London, United Kingdom, E14 5HU" },
            { "type": "text", "name": "CE类：欧盟进口商信息（本体）", "content": "For EU\nEU Importer Name: Whaleco Technology Limited\nEU Importer Address: First Floor, 25 St Stephens Green, Dublin 2, Ireland" },
            { "type": "text", "name": "英国进口商信息（本体）", "content": "For UK\nUK Importer Name: Whaleco UK Limited\nUK Importer Address: 5 Churchill Place, 10th Floor, London, United Kingdom, E14 5HU" },
            { "type": "text", "name": "土耳其标签合规-制造商名称，地址", "content": "Üretici: \nÜretici Adres：" },
            { "type": "text", "name": "土耳其标签合规-产品可追踪元素", "sub": "生产批次号/型号/序列号", "content": "Parti Numarası: Seri numarası:" },
            { "type": "text", "name": "制造商名称与地址", "sub": "需与申报信息一致", "content": "Manufacturer: \nAddress:" },
            { "type": "text", "name": "生产批号/型号/序列号", "sub": "需与申报信息一致", "content": "Batch Number：" },
            { "type": "image", "name": "欧盟 CE 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/221-ce.png" },
            { "type": "image", "name": "美国 FCC 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/221-fc.png" },
            { "type": "image", "name": "英国 UKCA 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/221-ukca.png" },
            { "type": "image", "name": "欧盟食品接触材料安全认证", "img": "https://recruit-student.51miniapps.com/tool/icon/222-bz.png" },
            { "type": "image", "name": "环保标志，商品可回收利用", "img": "https://recruit-student.51miniapps.com/tool/icon/221-qiu.png" },
            { "type": "image", "name": "欧盟不带电池的废弃电子电器回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/221-lj1.png" },
            { "type": "image", "name": "欧盟电池回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/222-lj2.png" },
            { "type": "image", "name": "欧盟标志", "img": "https://recruit-student.51miniapps.com/tool/icon/221-eu.png" },
            { "type": "image", "name": "欧洲共同体标志", "img": "https://recruit-student.51miniapps.com/tool/icon/221-ec.png" },
            { "type": "image", "name": "危险警示标签", "img": "https://recruit-student.51miniapps.com/tool/icon/227-Warning.png" },
            { "type": "image", "name": "危险警示标签", "img": "https://recruit-student.51miniapps.com/tool/icon/227-Warnings.png" },
            { "type": "image", "name": "填写数字+（以上的人群使用）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-round.png" },
            { "type": "image", "name": "禁止0-1岁儿童接触", "img": "https://recruit-student.51miniapps.com/tool/icon/227-01.png" },
            { "type": "image", "name": "禁止0-3岁儿童接触", "img": "https://recruit-student.51miniapps.com/tool/icon/227-03.png" },
            { "type": "image", "name": "禁止0-3岁儿童接触", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_6.png" },
            { "type": "image", "name": "禁止0-6岁儿童接触", "img": "https://recruit-student.51miniapps.com/tool/icon/227-06.png" },
            { "type": "image", "name": "通用可回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/227-environmentala.png" },
            { "type": "image", "name": "聚氯乙烯（PVC）回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/227-3pvc.png" },
            { "type": "image", "name": "低密度聚乙烯（PE-LD）回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/1/227-4peld.png" },
            { "type": "image", "name": "聚丙烯（PP）回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/227-5pp.png" },
            { "type": "image", "name": "聚苯乙烯（PS）回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/227-6ps.png" },
            { "type": "image", "name": "带有盖子且可开启的容器", "img": "https://recruit-student.51miniapps.com/tool/icon/227-empty.png" },
            { "type": "image", "name": "建议开封 6 个月内使用完毕", "img": "https://recruit-student.51miniapps.com/tool/icon/227-6M.png" },
            { "type": "image", "name": "建议开封 12 个月内使用完毕", "img": "https://recruit-student.51miniapps.com/tool/icon/227-12M.png" },
            { "type": "image", "name": "投放回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/227-Littering.png" },
            { "type": "image", "name": "通用可回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_13.png" },
            { "type": "image", "name": "日本 PSE 菱形标志", "img": "https://recruit-student.51miniapps.com/tool/icon/227-PSE.png" },
            { "type": "image", "name": "中国强制性产品认证（CCC）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ccc.png" },
            { "type": "image", "name": "美国儿童产品证书（CPC）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-cpc.png" },
            { "type": "image", "name": "美国 FDA 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/227-FDA.png" },
            { "type": "image", "name": "美国 UL 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/227-UL.png" },
            { "type": "image", "name": "美国和加拿大双重标准 UL 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_12.png" },
            { "type": "image", "name": "美国 ETL 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ETL.png" },
            { "type": "image", "name": "海湾 GCC 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/227-GCC.png" },
            { "type": "image", "name": "韩国 KC 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_3.png" },
            { "type": "image", "name": "中国 QS 质量安全认证", "img": "https://recruit-student.51miniapps.com/tool/icon/227-QS.png" },
            { "type": "image", "name": "日本 TELEC 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_1.png" },
            { "type": "image", "name": "日本 MIC 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_2.png" },
            { "type": "image", "name": "热表面警告", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_4.png" },
            { "type": "image", "name": "热表面警告", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_7.png" },
            { "type": "image", "name": "易燃危险物品", "img": "https://recruit-student.51miniapps.com/tool/icon/227-fireproof.png" },
            { "type": "image", "name": "让儿童在水环境中受到监督", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_5.png" },
            { "type": "image", "name": "含有电池产品的警告标志", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_11.png" },
            { "type": "image", "name": "放在儿童接触不到的地方", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_9.png" },
            { "type": "image", "name": "直流电源标志", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_8.png" },
            { "type": "image", "name": "双重绝缘（无需地线）", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_10.png" },
            { "type": "image", "name": "欧盟 RoHS 标志", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_14.png" },
            { "type": "image", "name": "欧盟 RoHS 标志", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_24.png" },
            { "type": "image", "name": "欧盟 RoHS 标志", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_33.png" },
            { "type": "image", "name": "进口商", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_23.png" },
            { "type": "image", "name": "不适合驾驶和道路使用", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_26.png" },
            { "type": "image", "name": "不适合驾驶和道路使用", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_25.png" },
            { "type": "image", "name": "避免窒息危险，请将袋子远离婴儿和儿童", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_32.png" },
            { "type": "image", "name": "美国 Soy Ink 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_31.png" },
            { "type": "image", "name": "美国 FCC 符合声明", "img": "https://recruit-student.51miniapps.com/tool/icon/221-content.png" },
            { "type": "image", "name": "儿童玩具警示语", "img": "https://recruit-student.51miniapps.com/tool/icon/221-warn2.png" },
            { "type": "image", "name": "窒息危险警示", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_15.png" },
            { "type": "image", "name": "法国 Triman 标识（纺织品）", "img": "https://recruit-student.51miniapps.com/tool/icon/221-bf.png" },
            { "type": "image", "name": "法国 Triman 标识（包装）", "img": "https://recruit-student.51miniapps.com/tool/icon/221-1f.png" },
            { "type": "image", "name": "法国 Triman 标识（电器）", "img": "https://recruit-student.51miniapps.com/tool/icon/221-2f.png" },
            { "type": "image", "name": "法国 Triman 标识（玩具）", "img": "https://recruit-student.51miniapps.com/tool/icon/221-3f.png" },
            { "type": "image", "name": "纽扣/硬币电池吞食危险警示", "img": "https://recruit-student.51miniapps.com/tool/icon/221-warn1.png" },
            { "type": "image", "name": "纽扣/硬币电池吞食危险警示", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_16.png" },
            { "type": "image", "name": "弹性行李带警告标签", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_34.png" },
            { "type": "image", "name": "窒息危险警示语-3至6岁含小部件", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_36.png" },
            { "type": "image", "name": "滤光片类别编号为0", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_37.png" },
            { "type": "image", "name": "滤光片类别编号为1", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_38.png" },
            { "type": "image", "name": "滤光片类别编号为2", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_39.png" },
            { "type": "image", "name": "滤光片类别编号为3", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_40.png" },
            { "type": "image", "name": "滤光片类别编号为4", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_41.png" },
            { "type": "image", "name": "环保标识", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_42.png" },
            { "type": "image", "name": "重型包裹标识", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_43.png" }
        ]
    },
    {
        "groupTitle": "法国标",
        "items": [
            { "type": "image", "name": "法国 Triman 标识", "img": "https://recruit-student.51miniapps.com/tool/icon/2/france_1.png" },
            { "type": "image", "name": "法国 Triman 标识（包装）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-triman-bg.png" },
            { "type": "image", "name": "法国 Triman 标识（包装）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-triman-fr.png" },
            { "type": "image", "name": "法国 Triman 标识（包装）", "img": "https://recruit-student.51miniapps.com/tool/icon/2/france_6.png" },
            { "type": "image", "name": "法国 Triman 标识（包装）", "img": "https://recruit-student.51miniapps.com/tool/icon/2/france_7.png" },
            { "type": "image", "name": "法国 Triman 标识（纺织品）", "img": "https://recruit-student.51miniapps.com/tool/icon/221-bf.png" },
            { "type": "image", "name": "法国 Triman 标识（纺织品）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-triman-fzp.png" },
            { "type": "image", "name": "法国 Triman 标识（电器）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-triman-epr.png" },
            { "type": "image", "name": "法国 Triman 标识（玩具）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-triman-wj.png" },
            { "type": "image", "name": "法国 Triman 标识（电器）", "img": "https://recruit-student.51miniapps.com/tool/icon/221-2f.png" },
            { "type": "image", "name": "法国 Triman 标识（电器）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-triman-dq.png" },
            { "type": "image", "name": "法国 Triman 标识（电器）", "img": "https://recruit-student.51miniapps.com/tool/icon/2/france_2.png" },
            { "type": "image", "name": "法国 Triman 标识（电器）", "img": "https://recruit-student.51miniapps.com/tool/icon/2/france_3.png" },
            { "type": "image", "name": "法国 Triman 标识（包装）", "img": "https://recruit-student.51miniapps.com/tool/icon/2/france_8.png" },
            { "type": "image", "name": "法国 Triman 标识（纺织品）", "img": "https://recruit-student.51miniapps.com/tool/icon/2/france_4.png" },
            { "type": "image", "name": "法国 Triman 标识（纺织品）", "img": "https://recruit-student.51miniapps.com/tool/icon/2/france_5.png" }
        ]
    },
    {
        "groupTitle": "西班牙包装标",
        "items": [
            { "type": "image", "name": "黄（塑料、金属或硬纸盒）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_recicla_yellow.png" },
            { "type": "image", "name": "蓝（纸、纸板或瓦愣纸）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_recycling_blue.png" },
            { "type": "image", "name": "棕（可降解包装）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_composta_brown.png" },
            { "type": "image", "name": "绿（玻璃）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_recicla_green.png" },
            { "type": "image", "name": "黄（塑料、金属或硬纸盒）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_ai_amarillo.png" },
            { "type": "image", "name": "蓝（纸、纸板或瓦愣纸）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_ai_azul.png" },
            { "type": "image", "name": "棕（可降解包装）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_ai_marron.png" },
            { "type": "image", "name": "绿（玻璃）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_ai_verde.png" },
            { "type": "image", "name": "黄（塑料、金属或硬纸盒）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_recicla_ai_amarillo_yellow.png" },
            { "type": "image", "name": "蓝（纸、纸板或瓦愣纸）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_recicla_ai_azul_blue.png" },
            { "type": "image", "name": "棕（可降解包装）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_composta_ai_marron_brown.png" },
            { "type": "image", "name": "绿（玻璃）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_recicla_ai_verde_green.png" },
            { "type": "image", "name": "黄（塑料、金属或硬纸盒）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_recicla_ai_amarillo.png" },
            { "type": "image", "name": "蓝（纸、纸板或瓦愣纸）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_recicla_ai_azul.png" },
            { "type": "image", "name": "棕（可降解包装）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_composta_ai_marron.png" },
            { "type": "image", "name": "绿（玻璃）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/spain_recicla_ai_verde.png" },
            { "type": "image", "name": "蓝+绿（纸+玻璃）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_greend_A1.png" },
            { "type": "image", "name": "蓝+绿（纸+玻璃）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_greend_A2.png" },
            { "type": "image", "name": "蓝+绿（纸+玻璃）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_greend_B1.png" },
            { "type": "image", "name": "蓝+绿（纸+玻璃）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_greend_B1-1.png" },
            { "type": "image", "name": "蓝+黄（纸+金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Metal_A1.png" },
            { "type": "image", "name": "蓝+黄（纸+金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Metal_A2.png" },
            { "type": "image", "name": "蓝+黄（纸+金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Metal_B1.png" },
            { "type": "image", "name": "蓝+黄（纸+金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Metal_B2.png" },
            { "type": "image", "name": "蓝+黄（纸+塑料）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Plastico_A1.png" },
            { "type": "image", "name": "蓝+黄（纸+塑料）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Plastico_A2.png" },
            { "type": "image", "name": "蓝+黄（纸+塑料）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Plastico_B1.png" },
            { "type": "image", "name": "蓝+黄（纸+塑料）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Plastico_B2.png" },
            { "type": "image", "name": "绿+黄（玻璃+金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_greend_yellow_Metal_A1.png" },
            { "type": "image", "name": "绿+黄（玻璃+金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_greend_yellow_Metal_A2.png" },
            { "type": "image", "name": "绿+黄（玻璃+金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_greend_yellow_Metal_B1.png" },
            { "type": "image", "name": "绿+黄（玻璃+金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_greend_yellow_Metal_B2.png" },
            { "type": "image", "name": "绿+黄（玻璃+塑料）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_greend_yellow_Plastico_A1.png" },
            { "type": "image", "name": "绿+黄（玻璃+塑料）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_greend_yellow_Plastico_A2.png" },
            { "type": "image", "name": "绿+黄（玻璃+塑料）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_greend_yellow_Plastico_B1.png" },
            { "type": "image", "name": "绿+黄（玻璃+塑料）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_greend_yellow_Plastico_B2.png" },
            { "type": "image", "name": "蓝+黄（纸+塑料/金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Plastico_Metal_A1.png" },
            { "type": "image", "name": "蓝+黄（纸+塑料/金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Plastico_Metal_A2.png" },
            { "type": "image", "name": "蓝+黄（纸+塑料/金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Plastico_Metal_B1.png" },
            { "type": "image", "name": "蓝+黄（纸+塑料/金属）", "img": "https://recruit-student.51miniapps.com/tool/icon/12/Spain_blue_yellow_Plastico_Metal_B2.png" }
        ]
    },
    {
        "groupTitle": "化妆品",
        "items": [
            { "type": "image", "name": "通用可回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/227-environmentala.png" },
            { "type": "image", "name": "聚氯乙烯（PVC）回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/227-3pvc.png" },
            { "type": "image", "name": "聚丙烯（PP）回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/227-5pp.png" },
            { "type": "image", "name": "聚苯乙烯（PS）回收标志", "img": "https://recruit-student.51miniapps.com/tool/icon/227-6ps.png" },
            { "type": "image", "name": "带有盖子且可开启的容器", "img": "https://recruit-student.51miniapps.com/tool/icon/227-empty.png" },
            { "type": "image", "name": "建议开封 6 个月内使用完毕", "img": "https://recruit-student.51miniapps.com/tool/icon/227-6M.png" },
            { "type": "image", "name": "建议开封 12 个月内使用完毕", "img": "https://recruit-student.51miniapps.com/tool/icon/227-12M.png" },
            { "type": "image", "name": "建议开封 24 个月内使用完毕", "img": "https://recruit-student.51miniapps.com/tool/icon/3/24M.png" },
            { "type": "image", "name": "建议开封 36 个月内使用完毕", "img": "https://recruit-student.51miniapps.com/tool/icon/3/36M.png" },
            { "type": "image", "name": "禁止接触眼睛", "img": "https://recruit-student.51miniapps.com/tool/icon/227-eye.png" },
            { "type": "image", "name": "需阅读说明书", "img": "https://recruit-student.51miniapps.com/tool/icon/227-book.png" },
            { "type": "image", "name": "欧盟无动物测试标志", "img": "https://recruit-student.51miniapps.com/tool/icon/3/eu_no_animal_test_mark.png" },
            { "type": "image", "name": "欧盟净含量", "img": "https://recruit-student.51miniapps.com/tool/icon/3/en_net_content.png" }
        ]
    },
    {
        "groupTitle": "鞋类",
        "items": [
            { "type": "image", "name": "织物（真丝、亚麻、棉、化纤等）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-lqbz.png" },
            { "type": "image", "name": "合成材料（人造革等）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-mfx.png" },
            { "type": "image", "name": "覆膜皮革（二层牛皮等）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xfx.png" },
            { "type": "image", "name": "真皮", "img": "https://recruit-student.51miniapps.com/tool/icon/227-zfx.png" },
            { "type": "image", "name": "鞋底", "img": "https://recruit-student.51miniapps.com/tool/icon/227-shoe1.png" },
            { "type": "image", "name": "衬里和内底", "img": "https://recruit-student.51miniapps.com/tool/icon/227-shoe2.png" },
            { "type": "image", "name": "鞋面", "img": "https://recruit-student.51miniapps.com/tool/icon/227-shoe3.png" },
            { "type": "image", "name": "全鞋", "img": "https://recruit-student.51miniapps.com/tool/icon/4/shoes_1.png" }
        ]
    },
    {
        "groupTitle": "纽扣电池",
        "items": [
            { "type": "image", "name": "含有电池产品的警告标志", "img": "https://recruit-student.51miniapps.com/tool/icon/10/battery_4.png" },
            { "type": "image", "name": "放在儿童接触不到的地方", "img": "https://recruit-student.51miniapps.com/tool/icon/10/battery_5.png" },
            { "type": "image", "name": "纽扣/硬币电池吞食危险警示-带电话", "img": "https://recruit-student.51miniapps.com/tool/icon/10/battery_1.png" },
            { "type": "image", "name": "纽扣/硬币电池吞食危险警示-带电话", "img": "https://recruit-student.51miniapps.com/tool/icon/10/battery_2.png" },
            { "type": "image", "name": "纽扣/硬币电池吞食危险警示", "img": "https://recruit-student.51miniapps.com/tool/icon/10/battery_6.png" },
            { "type": "image", "name": "纽扣/硬币电池吞食危险警示", "img": "https://recruit-student.51miniapps.com/tool/icon/10/battery_8.png" },
            { "type": "image", "name": "纽扣/硬币电池吞食危险警示", "img": "https://recruit-student.51miniapps.com/tool/icon/10/battery_7.png" },
            { "type": "image", "name": "纽扣/硬币电池吞食危险警示-组合", "img": "https://recruit-student.51miniapps.com/tool/icon/10/battery_3.png" }
        ]
    },
    {
        "groupTitle": "欧盟能效",
        "items": [
            { "type": "image", "name": "欧盟", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_1.png" },
            { "type": "image", "name": "能源标志", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_15.png" },
            { "type": "image", "name": "欧盟能源标志", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_2.png" },
            { "type": "image", "name": "自定义能效", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_3.png" },
            { "type": "image", "name": "能效 A", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_9.png" },
            { "type": "image", "name": "能效 B", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_19.png" },
            { "type": "image", "name": "能效 C", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_11.png" },
            { "type": "image", "name": "能效 D", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_13.png" },
            { "type": "image", "name": "能效 E", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_18.png" },
            { "type": "image", "name": "能效 F", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_17.png" },
            { "type": "image", "name": "能效 G", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_7.png" },
            { "type": "image", "name": "能效等级", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_12.png" },
            { "type": "image", "name": "自定义能效等级", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_10.png" },
            { "type": "image", "name": "自定义能效等级", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_14.png" },
            { "type": "image", "name": "欧盟能效标识排版", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_8.png" },
            { "type": "image", "name": "带希腊文的欧盟能效标识排版", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_6.png" },
            { "type": "image", "name": "欧盟能效标识排版", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_5.png" },
            { "type": "image", "name": "带希腊文的欧盟能效标识排版（扩充等级）", "img": "https://recruit-student.51miniapps.com/tool/icon/6/eu_energy_16.png" }
        ]
    },
    {
        "groupTitle": "医疗器械标",
        "items": [
            { "type": "image", "name": "操作说明书", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_1.png" },
            { "type": "image", "name": "单个患者多次使用", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_2.png" },
            { "type": "image", "name": "生产日期", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_3.png" },
            { "type": "image", "name": "湿度限制", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_4.png" },
            { "type": "image", "name": "朝上摆放", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_6.png" },
            { "type": "image", "name": "含有有害物质", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_7.png" },
            { "type": "image", "name": "远离阳光", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_8.png" },
            { "type": "image", "name": "欧盟 CE 认证", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_9.png" },
            { "type": "image", "name": "温度限制", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_10.png" },
            { "type": "image", "name": "如果包装损坏，请勿使用", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_12.png" },
            { "type": "image", "name": "制造商", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_15.png" },
            { "type": "image", "name": "含有药物", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_16.png" },
            { "type": "image", "name": "请勿重复使用", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_17.png" },
            { "type": "image", "name": "请勿重新灭菌", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_30.png" },
            { "type": "image", "name": "使用辐射灭菌", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_31.png" },
            { "type": "image", "name": "仅供研究使用，不得用于诊断程序", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_14.png" },
            { "type": "image", "name": "医疗器械标识", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_18.png" },
            { "type": "image", "name": "体外诊断医疗器械", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_5.png" },
            { "type": "image", "name": "批次编号", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_27.png" },
            { "type": "image", "name": "目录编号", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_28.png" },
            { "type": "image", "name": "序列编号", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_29.png" },
            { "type": "image", "name": "净数量", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_32.png" },
            { "type": "image", "name": "唯一设备标识符", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_33.png" },
            { "type": "image", "name": "欧洲代表（名字、地址、电话）", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_13.png" },
            { "type": "image", "name": "足够用于 n 次测试", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_19.png" },
            { "type": "image", "name": "使用截止日期", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_20.png" },
            { "type": "image", "name": "易碎品标志", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_21.png" },
            { "type": "image", "name": "生物风险", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_22.png" },
            { "type": "image", "name": "含有或存在天然橡胶乳胶", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_23.png" },
            { "type": "image", "name": "大气压力限制", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_24.png" },
            { "type": "image", "name": "远离雨水", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_25.png" },
            { "type": "image", "name": "非无菌", "img": "https://recruit-student.51miniapps.com/tool/icon/8/medical_26.png" }
        ]
    },
    {
        "groupTitle": "水洗标",
        "items": [
            { "type": "image", "name": "正常温度烘干（非常温和）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxjyoo55.png" },
            { "type": "image", "name": "烘干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyj43.png" },
            { "type": "image", "name": "低温烘干（常规）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyj44.png" },
            { "type": "image", "name": "正常温度烘干（常规）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyj45.png" },
            { "type": "image", "name": "高温烘干（常规）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyj46.png" },
            { "type": "image", "name": "正常温度烘干（温和）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyjey50.png" },
            { "type": "image", "name": "可烘干免熨烫", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyji52.png" },
            { "type": "image", "name": "低温烘干（非常温和）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyjiio54.png" },
            { "type": "image", "name": "轻柔烘干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyjiio57.png" },
            { "type": "image", "name": "高温烘干（非常温和）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyjiiooo56.png" },
            { "type": "image", "name": "高温烘干（温和）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyjsy51.png" },
            { "type": "image", "name": "请勿烘干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyjx58.png" },
            { "type": "image", "name": "可烘干免熨烫", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyjy48.png" },
            { "type": "image", "name": "低温烘干（温和）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtxyjyy49.png" },
            { "type": "image", "name": "烘干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-gtyxyjn47.png" },
            { "type": "image", "name": "悬挂晾干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-hb64.png" },
            { "type": "image", "name": "阴凉处悬挂晾干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-hbee65.png" },
            { "type": "image", "name": "羊毛纤维", "img": "https://recruit-student.51miniapps.com/tool/icon/227-mx42.png" },
            { "type": "image", "name": "轻轻拧扭", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ng100.png" },
            { "type": "image", "name": "不可拧扭脱水", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ngx101.png" },
            { "type": "image", "name": "低湿度干洗", "img": "https://recruit-student.51miniapps.com/tool/icon/227-O87.png" },
            { "type": "image", "name": "无蒸汽干洗", "img": "https://recruit-student.51miniapps.com/tool/icon/227-o88.png" },
            { "type": "image", "name": "低温干洗", "img": "https://recruit-student.51miniapps.com/tool/icon/227-o89.png" },
            { "type": "image", "name": "使用任何溶剂进行（常规干洗）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OA84.png" },
            { "type": "image", "name": "低湿度干洗（可使用任何溶剂）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OA90.png" },
            { "type": "image", "name": "无蒸汽干洗（可使用任何溶剂）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OA91.png" },
            { "type": "image", "name": "短时干洗（可使用任何溶剂）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OA92.png" },
            { "type": "image", "name": "低温干洗（可使用任何溶剂）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OA93.png" },
            { "type": "image", "name": "使用任何溶剂进行（温和干洗）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OA94.png" },
            { "type": "image", "name": "使用任何溶剂进行（非常温和干洗）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OAR97.png" },
            { "type": "image", "name": "使用碳氢化合物等进行（常规干洗）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OF85.png" },
            { "type": "image", "name": "使用碳氢化合物等进行（非常温和干洗）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OFE98.png" },
            { "type": "image", "name": "使用碳氢化合物等进行（温和干洗）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OFY95.png" },
            { "type": "image", "name": "使用四氯乙烯等进行（常规干洗）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OP86.png" },
            { "type": "image", "name": "使用四氯乙烯等进行（非常温和干洗）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OPE99.png" },
            { "type": "image", "name": "请勿干洗", "img": "https://recruit-student.51miniapps.com/tool/icon/227-opno82.png" },
            { "type": "image", "name": "使用四氯乙烯等进行（温和干洗）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-OPY96.png" },
            { "type": "image", "name": "可用任意漂白剂", "img": "https://recruit-student.51miniapps.com/tool/icon/227-qp76.png" },
            { "type": "image", "name": "允许使用氯漂白", "img": "https://recruit-student.51miniapps.com/tool/icon/227-qpcl78.png" },
            { "type": "image", "name": "只可用非氯性漂白剂", "img": "https://recruit-student.51miniapps.com/tool/icon/227-qpgg77.png" },
            { "type": "image", "name": "请勿漂白", "img": "https://recruit-student.51miniapps.com/tool/icon/227-qpno79.png" },
            { "type": "image", "name": "请勿漂白", "img": "https://recruit-student.51miniapps.com/tool/icon/227-qpnoo80.png" },
            { "type": "image", "name": "轻柔烘干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-stxyjii53.png" },
            { "type": "image", "name": "手洗", "img": "https://recruit-student.51miniapps.com/tool/icon/227-sx5.png" },
            { "type": "image", "name": "最高洗涤温度 95℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-tsjw24.png" },
            { "type": "image", "name": "最高洗涤温度 70℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-tsqs23.png" },
            { "type": "image", "name": "最高洗涤温度 95℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtjwe28.png" },
            { "type": "image", "name": "最高洗涤温度 60℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtls22.png" },
            { "type": "image", "name": "最高洗涤温度 30℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtpp6.png" },
            { "type": "image", "name": "最高洗涤温度 40℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtpp7.png" },
            { "type": "image", "name": "最高洗涤温度 50℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtpp8.png" },
            { "type": "image", "name": "最高洗涤温度 60℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtpp9.png" },
            { "type": "image", "name": "最高洗涤温度 70℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtpp10.png" },
            { "type": "image", "name": "最高洗涤温度 70℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtpp11.png" },
            { "type": "image", "name": "最高洗涤温度 95℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtpp12.png" },
            { "type": "image", "name": "最高洗涤温度 30℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtppe13.png" },
            { "type": "image", "name": "最高洗涤温度 40℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtppe14.png" },
            { "type": "image", "name": "最高洗涤温度 50℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtppe15.png" },
            { "type": "image", "name": "最高洗涤温度 95℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtppe16.png" },
            { "type": "image", "name": "最高洗涤温度 40℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtppe18.png" },
            { "type": "image", "name": "最高洗涤温度 60℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtppf20.png" },
            { "type": "image", "name": "最高洗涤温度 50℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtpps19.png" },
            { "type": "image", "name": "最高洗涤温度 30℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtppy6.png" },
            { "type": "image", "name": "机洗", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtsm1.png" },
            { "type": "image", "name": "请勿洗涤", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtsm2.png" },
            { "type": "image", "name": "免熨烫机洗", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtsm3.png" },
            { "type": "image", "name": "轻柔机洗", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtsm4.png" },
            { "type": "image", "name": "最高洗涤温度 30℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtssy25.png" },
            { "type": "image", "name": "最高洗涤温度 50℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/227-xtws21.png" },
            { "type": "image", "name": "可熨烫", "img": "https://recruit-student.51miniapps.com/tool/icon/227-yd66.png" },
            { "type": "image", "name": "不可蒸汽熨烫", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ydnosq72.png" },
            { "type": "image", "name": "低温熨烫，最高温度 110℃", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ydo68.png" },
            { "type": "image", "name": "中温熨烫，最高温度 150℃", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ydoo69.png" },
            { "type": "image", "name": "高温熨烫，最高温度 200℃", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ydooo70.png" },
            { "type": "image", "name": "蒸汽熨烫", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ydsq71.png" },
            { "type": "image", "name": "不可蒸汽熨烫，最高温度 110℃", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ydsqo73.png" },
            { "type": "image", "name": "不可蒸汽熨烫，最高温度 150℃", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ydsqoo74.png" },
            { "type": "image", "name": "不可蒸汽熨烫，最高温度 200℃", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ydsqooo75.png" },
            { "type": "image", "name": "不可熨烫", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ydx67.png" },
            { "type": "image", "name": "干洗", "img": "https://recruit-student.51miniapps.com/tool/icon/227-yp81.png" },
            { "type": "image", "name": "请勿干洗", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ypnoo83.png" },
            { "type": "image", "name": "阴凉处悬挂滴干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-yrteeiii63.png" },
            { "type": "image", "name": "阴凉处平放晾干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ytee61.png" },
            { "type": "image", "name": "悬挂滴干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ytiii62.png" },
            { "type": "image", "name": "请勿烘干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-ytx59.png" },
            { "type": "image", "name": "平放晾干", "img": "https://recruit-student.51miniapps.com/tool/icon/227-yty60.png" },
            { "type": "image", "name": "最高洗涤温度 50℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_2.png" },
            { "type": "image", "name": "最高洗涤温度 50℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_5.png" },
            { "type": "image", "name": "最高洗涤温度 60℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_6.png" },
            { "type": "image", "name": "最高洗涤温度 70℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_7.png" },
            { "type": "image", "name": "短时干洗", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_8.png" },
            { "type": "image", "name": "最高洗涤温度 60℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_9.png" },
            { "type": "image", "name": "最高洗涤温度 30℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_10.png" },
            { "type": "image", "name": "最高洗涤温度 70℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_11.png" },
            { "type": "image", "name": "最高洗涤温度 95℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_12.png" },
            { "type": "image", "name": "最高洗涤温度 70℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_14.png" },
            { "type": "image", "name": "最高洗涤温度 95℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_15.png" },
            { "type": "image", "name": "最高洗涤温度 40℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_16.png" },
            { "type": "image", "name": "悬挂滴干", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_17.png" },
            { "type": "image", "name": "最高洗涤温度 60℃（非常温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_18.png" },
            { "type": "image", "name": "阴凉处悬挂晾干", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_19.png" },
            { "type": "image", "name": "最高洗涤温度 30℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_20.png" },
            { "type": "image", "name": "悬挂晾干", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_21.png" },
            { "type": "image", "name": "阴凉处晾干，悬挂或平放", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_22.png" },
            { "type": "image", "name": "最高洗涤温度 40℃（温和洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_24.png" },
            { "type": "image", "name": "最高洗涤温度 40℃（常规洗涤）", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_25.png" },
            { "type": "image", "name": "不允许使用氯漂白", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_27.png" },
            { "type": "image", "name": "平放滴干", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_28.png" },
            { "type": "image", "name": "常规湿洗", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_29.png" },
            { "type": "image", "name": "温和湿洗", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_30.png" },
            { "type": "image", "name": "非常温和湿洗", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_31.png" },
            { "type": "image", "name": "请勿湿洗", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_32.png" },
            { "type": "image", "name": "阴凉处平放滴干", "img": "https://recruit-student.51miniapps.com/tool/icon/5/washing_33.png" }
        ]
    },
    {
        "groupTitle": "GHS全球危险品统一标识",
        "items": [
            { "type": "image", "name": "具有氧化性，能够加剧火势", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_2.png" },
            { "type": "image", "name": "易燃品标志", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_5.png" },
            { "type": "image", "name": "易燃品标志", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_10.png" },
            { "type": "image", "name": "易燃气体", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_28.png" },
            { "type": "image", "name": "易燃液体", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_29.png" },
            { "type": "image", "name": "易燃固体、自反应物质和固体退敏爆炸品", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_24.png" },
            { "type": "image", "name": "遇水放出易燃气体的物质和混合物", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_30.png" },
            { "type": "image", "name": "发火物质", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_25.png" },
            { "type": "image", "name": "氧化性物质", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_26.png" },
            { "type": "image", "name": "有机过氧化物", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_3.png" },
            { "type": "image", "name": "剧毒物标志", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_4.png" },
            { "type": "image", "name": "有毒气体", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_7.png" },
            { "type": "image", "name": "有毒物品", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_6.png" },
            { "type": "image", "name": "腐蚀性物质", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_11.png" },
            { "type": "image", "name": "腐蚀品标志", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_13.png" },
            { "type": "image", "name": "腐蚀品标志", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_33.png" },
            { "type": "image", "name": "对环境危害", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_32.png" },
            { "type": "image", "name": "对健康危害", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_9.png" },
            { "type": "image", "name": "爆炸品标志", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_15.png" },
            { "type": "image", "name": "爆炸物 1.2项", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_20.png" },
            { "type": "image", "name": "爆炸物 1.4 项", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_27.png" },
            { "type": "image", "name": "爆炸物 1.5 项", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_14.png" },
            { "type": "image", "name": "爆炸物 1.6 项", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_12.png" },
            { "type": "image", "name": "警告标志", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_16.png" },
            { "type": "image", "name": "警告标志", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_18.png" },
            { "type": "image", "name": "压缩气体或液化气体", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_23.png" },
            { "type": "image", "name": "非易燃、无毒气体", "img": "https://recruit-student.51miniapps.com/tool/icon/7/ghs_danger_31.png" }
        ]
    },
    {
        "groupTitle": "CCCR危害符号",
        "items": [
            { "type": "image", "name": "有毒", "img": "https://recruit-student.51miniapps.com/tool/icon/15/CCCR_1.png" },
            { "type": "image", "name": "腐蚀性", "img": "https://recruit-student.51miniapps.com/tool/icon/15/CCCR_2.png" },
            { "type": "image", "name": "易燃", "img": "https://recruit-student.51miniapps.com/tool/icon/15/CCCR_3.png" },
            { "type": "image", "name": "易爆", "img": "https://recruit-student.51miniapps.com/tool/icon/15/CCCR_4.png" }
        ]
    },
    {
        "groupTitle": "电子电器",
        "items": [
            { "type": "image", "name": "配备了USB Type-C充电器", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_27.png" },
            { "type": "image", "name": "未配备USB Type-C充电器", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_28.png" },
            { "type": "image", "name": "不支持USB PD快充", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_30.png" },
            { "type": "image", "name": "支持USB PD快充", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_29.png" },
            { "type": "image", "name": "法国可修复性指数", "img": "https://recruit-student.51miniapps.com/tool/icon/13/REPARABILITE_1.png" },
            { "type": "image", "name": "法国可修复性指数", "img": "https://recruit-student.51miniapps.com/tool/icon/13/REPARABILITE_2.png" },
            { "type": "image", "name": "法国可修复性指数", "img": "https://recruit-student.51miniapps.com/tool/icon/13/REPARABILITE_3.png" },
            { "type": "image", "name": "法国可修复性指数", "img": "https://recruit-student.51miniapps.com/tool/icon/13/REPARABILITE_4.png" },
            { "type": "image", "name": "法国可修复性指数", "img": "https://recruit-student.51miniapps.com/tool/icon/13/REPARABILITE_5.png" },
            { "type": "image", "name": "法国可修复性指数", "img": "https://recruit-student.51miniapps.com/tool/icon/13/REPARABILITE_6.png" },
            { "type": "image", "name": "法国可修复性指数 0-1.9", "img": "https://recruit-student.51miniapps.com/tool/icon/13/REPARABILITE_0-1.9.png" },
            { "type": "image", "name": "法国可修复性指数 2-3.9", "img": "https://recruit-student.51miniapps.com/tool/icon/13/REPARABILITE_2-3.9.png" },
            { "type": "image", "name": "法国可修复性指数 4-5.9", "img": "https://recruit-student.51miniapps.com/tool/icon/13/REPARABILITE_4-5.9.png" },
            { "type": "image", "name": "法国可修复性指数 6-7.9", "img": "https://recruit-student.51miniapps.com/tool/icon/13/REPARABILITE_6-7.9.png" },
            { "type": "image", "name": "法国可修复性指数 8-10", "img": "https://recruit-student.51miniapps.com/tool/icon/13/REPARABILITE_8-10.png" },
            { "type": "image", "name": "III类设备", "img": "https://recruit-student.51miniapps.com/tool/icon/1/general_35.png" }
        ]
    },
    {
        "groupTitle": "家具类",
        "items": [
            { "type": "image", "name": "店内警告-类别1", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_1.png" },
            { "type": "image", "name": "店内警告-类别2", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_2.png" },
            { "type": "image", "name": "店内警告-类别3", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_3.png" },
            { "type": "image", "name": "在线警告-类别1", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_4.png" },
            { "type": "image", "name": "在线警告-类别2", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_5.png" },
            { "type": "image", "name": "在线警告-类别3", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_6.png" },
            { "type": "image", "name": "产品警告标签-类别1", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_7.png" },
            { "type": "image", "name": "产品警告标签-类别2", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_8.png" },
            { "type": "image", "name": "产品警告标签-类别3", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_9.png" },
            { "type": "image", "name": "带有警告说明-类别1", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_10.png" },
            { "type": "image", "name": "带有警告说明-类别2", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_11.png" },
            { "type": "image", "name": "带有警告说明-类别3", "img": "https://recruit-student.51miniapps.com/tool/icon/14/furniture_12.png" }
        ]
    }
];
